# For Reference: https://docs.travis-ci.com/user/languages/javascript-with-nodejs

language: node_js
node_js:
  - "6"
  - "5"

sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

# Matrix failure enabled for https://github.com/TheLarkInn/LazyParseWebpackPlugin/issues/6

matrix:
  fast_finish: true
  allow_failures:

install:
  - npm install

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - npm run lint
  - npm test
  # - npm run build:prod
  # - npm run server:prod:ci &
  # - sleep 3
  # - npm run e2e
